Last Used Profile: ""
Auto-Connect: false
Profiles:
    - Name: "Local"
      Host: localhost
      Port: 1142
      Username: "user"
      Password: "pass"
    - Name: "Internal"
      Host: <internal>
      Port:
      Username:
      Password:
